server:
  port: 3000

db:
  type: 'mysql'
  port: 3306
  database: 'aqu'
  username: 'root'
  host: 'localhost'
  password: 'op1928!!'
  synchronize: true

jwt:
  expiration: '3m'
  secret: 'serverofaqu'
  refreshSecret: "refreshaqu"
  refreshExpiration: '50000000'